### ISSUE TITLE
IOS system support？

### ISSUE THREAD

**Issue by walletsh** [will-lumley/RichEditor#1]
I want to use it on iPad and iPhone. Can I support it?

**Comment by will-lumley** [comment]
Hey @walletsh - thanks for the question!
Unfortunately this framework is macOS only, for now.


There are similar iOS frameworks, such as [SQRichTextEditor](https://github.com/OneupNetwork/SQRichTextEditor) that may suit your needs.


If they don't suit your needs, let me know if you're interested in an iOS equivalent of this.
