### ISSUE TITLE
Swift Package Manager Installation Fails: Source files for target RichEditor should be located under 'Sources/RichEditor'…

### ISSUE THREAD

**Issue by 101airborne** [will-lumley/RichEditor#3]
All attempts to use Swift Packager Manager to add RichEditor to my project fail.

I've added RichEditor in Xcode/Project/Project Dependencies using url:  https://github.com/will-lumley/RichEditor.git

resulting in:

![SPM_RichEditor_error](https://github.com/will-lumley/RichEditor/assets/4751331/83fafe76-6666-4705-ae56-7ed7b2788bec)

I selected "Add Anyway" and the package is added.  But the project will not build.  Xcode complains:  **Source files for target RichEditor should be located under 'Sources/RichEditor', or a custom sources path can be set with the 'path' property in Package.swift**

All of my attempts to correct this issue have failed.  I have tried on macOS Catalina/Xcode 12.4, Monterey/Xcode 14.2, and Ventura /Xcode 15.2.

Any help with this issue would be greatly appreciated.

**Comment by will-lumley** [comment]
Thanks @101airborne for getting in touch! I'll be having a look at this issue tonight (it's morning for me atm). Shouldn't be a huge fix. I'll reach out here once it's resolved.

**Comment by 101airborne** [comment]
Thanks Will.  SPM integration is working perfectly now!
